# Generated by Django 4.0.5 on 2022-07-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesadmin',
            name='a',
        ),
    ]
